config/routes.rb
Rails.application.routes.draw do
  get    'password_resets/new'
  get    'password_resets/edit'
  root   'static_pages#home'
  get    '/dmhome',  to: 'static_pages#dmhome'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :dmessages
    end
  end
  resources :memberships,          only: :destroy
  resources :dmessages,            only: :destroy
  resources :likes, only: [:create, :destroy]
  
  resources :categories, only: [] do
    resources :sub_categories, only: :index
  end
end

app/models/talk.rb
class Talk < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, class_name: "User", through: :memberships, source: :user
  has_many :dmessages, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  
  # メンバーのユーザー名を", "で連結した文字列を指定した長さで返す。
  def title(current_user, length=100)
    counter = " (#{members.count})"
    length -= counter.length
    other_members = members.select{ |member| current_user != member }
    title = other_members.collect{ |member| member.name }.join(', ')
    title = title[0...length] + '...' if title.length > length
    if other_members.count > 2
      title + counter
    else
      title
    end
  end
  
  def latest_message
    dmessages.last if dmessages.count > 0
  end
  
  # トークから退出する
  def leave(user)
    membership = memberships.find_by(user: user)
    return false if membership.nil?
    !!(membership.destroy)
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :logged_in_user
  before_action :correct_member, only: [:show, :dmessages]
  
  def show
    @dmessages = @talk.dmessages
    @dmessage = Dmessage.new
  end
  
  def create
    @talk = Talk.new
    @talk.memberships.build(user_id: current_user.id)
    @talk.memberships.build(user_id: params[:member_id])
    @talk.save
    redirect_to @talk
  end
  
  def dmessages
    @dmessage = Dmessage.new(dmessage_params)
    # トークの更新日時を更新
    @talk.touch
    if @dmessage.save
      redirect_to @talk
    else
      @dmessages = @talk.dmessages
      render "show"
    end
  end
  
  private
    
  def dmessage_params
    params[:dmessage].merge!({ user_id: current_user.id, talk_id: @talk.id })
    params.require(:dmessage).permit(:user_id, :talk_id, :content)
  end
    
  def correct_member
    @talk = current_user.talks.find_by(id: params[:id])
    redirect_to root_url if @talk.nil?
  end
    
  def correct_user
    @dmessage = current_user.dmessages.find_by(id: params[:id])
    redirect_to root_url if @dmessage.nil?
  end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_talk.html.erb
<li id="talk-<%=talk.id%>" class="ulbackcolor">
  <% dmessage = talk.latest_message %>
  <% membership = talk.memberships.find_by(user: current_user) %>
  <%= gravatar_for(dmessage.nil? ? talk.memberships.first.user : dmessage.user, size: 50) %>
  <%= link_to 'leave', membership_path(membership),
                                    class: "delete",
                                    method: :delete,
                                    data: { confirm: "トークルームを削除します。よろしいですか？" } %>
  <%= link_to(talk) do %>
    <span class="title" id=dmessagetitle><%= talk.title(current_user, 50) %></span>
    <span class="content"><%= dmessage.content unless dmessage.nil? %></span>
    <span class="timestamp">
      投稿 <%= time_ago_in_words(talk.updated_at) %> 前
    </span>
  <% end %>
</li>

app/views/talks/show.html.erb
<% title = @talk.title(current_user, 50) %>
<% provide(:title, title) %>
<body class="main">
  <h1 class="subtitle"><%= title %></h1>
  <div class="row" >
    <div class="col-md-2">
      <h1 class="ml16">Talk Room</h1>
      <script src="//cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
      <%= javascript_include_tag('anime3.js') %>
    </div>
    <div class="col-md-8">
      <ul class="dmessages ulbackcolor">
        <%= render @dmessages %>
      </ul>
      <%= form_for @dmessage, url: dmessages_talk_path(@talk),
                            html: { class: 'dmessage-form'} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, class: "content" %>
      </div>
      <%= f.submit "Send", class: "btn btn-primary btntextsize" %>
      <% end %>
    </div>
  </div>
</body>