config/routes.rb
Rails.application.routes.draw do
  get    'password_resets/new'
  get    'password_resets/edit'
  root   'static_pages#home'
  get    '/dmhome',  to: 'static_pages#dmhome'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :dmessages
    end
  end
  resources :memberships,          only: :destroy
  resources :dmessages,            only: :destroy
  resources :likes, only: [:create, :destroy]
  
  resources :categories, only: [] do
    resources :sub_categories, only: :index
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     <%= t('.errors count', errors_count: object.errors.count) %>
    </div>
    <ul class="ulerrorbackcolor">
    <% object.errors.full_messages.each do |message| %>
      <li class="lierror"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts ulbackcolor">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "新しいtweetをしよう！" %>
  </div>
  <%= f.submit "Tweet", class: "btn btn-primary btntextsize" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイルサイズが大きすぎます。最大５MBです。');
    }
  });
</script>

app/views/shared/_microposts_search_form.html.erb
<%= search_form_for @q, url: @url do |f| %>
  <%= f.label :content_cont, '  Tweet検索' ,class: 'color'%>
  <div class="input-group">
    <%= f.text_field :content_cont, placeholder: "キーワードを入れてください。",
                      class: 'form-control' %>
    <span class="input-group-btn">
     <%= f.submit 'Go', class: "btn btn-primary btntextsize" %>
    </span>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>" id="linkcolor">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    Follows
  </a>
  <a href="<%= followers_user_path(@user) %>" id="linkcolor">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/shared/_talks.html.erb
<% if @talks.any? %>
  <ol class="talks">
    <%= render @talks %>
  </ol>
  <%= will_paginate @talks%>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1 class = "color2"><%= current_user.name %></h1>
<span><%= link_to "マイアカウントを表示", current_user ,class:"linkcolor"%></span>
<span class = "color2"><%= pluralize(current_user.microposts.count, "tweet") %></span>