config/routes.rb
Rails.application.routes.draw do
  get    'password_resets/new'
  get    'password_resets/edit'
  root   'static_pages#home'
  get    '/dmhome',  to: 'static_pages#dmhome'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :dmessages
    end
  end
  resources :memberships,          only: :destroy
  resources :dmessages,            only: :destroy
  resources :likes, only: [:create, :destroy]
  
  resources :categories, only: [] do
    resources :sub_categories, only: :index
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class="logo">
      <li><%= link_to image_tag('/serieA.png', class: "ligu_logo"), "http://www.legaseriea.it/it/",target: :_blank %></li>
      <li><%= link_to image_tag('/premier.png', class: "ligu_logo"), "https://www.premierleague.com//",target: :_blank %></li>
      <li><%= link_to image_tag('/j.png', class: "ligu_logo"), "https://www.jleague.jp//",target: :_blank %></li>
      <li><%= link_to image_tag('/ligue1.png', class: "ligu_logo"), "https://www.ligue1.com//",target: :_blank %></li>
      <li><%= link_to image_tag('/laliga.png', class: "ligu_logo"), "https://www.laliga.com//",target: :_blank  %></li>
      <li><%= link_to image_tag('/bundes.png', class: "ligu_logo"), "https://www.bundesliga.com/jp/bundesliga/",target: :_blank  %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//unpkg.com/swiper/css/swiper.min.css">
    <script src="//unpkg.com/swiper/js/swiper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'load' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'load' %>
    <%= javascript_include_tag('select.js') %>
    <%= javascript_include_tag('rollsraid.js') %>
    <%= render 'layouts/shim' %>
  </head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background: rgba(0,0,64,0.5);">
  <div class="container">
    <%= link_to "WSC", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right"　style="background-color:#000066;">
        <% if logged_in? %>        
          <li><%= link_to "Direct Message", dmhome_path %></li>
          <li><%= link_to "Tweet", root_path %></li>
          <li><%= link_to "Supporters", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
         <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
         </script>
            <ul class="dropdown-menu">
              <li><%= link_to "My Account", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>